language: android
android:
  components:
    - platform-tools
    - tools
    - extra
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - sys-img-x86-android-23

script:
  - ./gradlew check test connectedCheck

